Repository team-azito/spring-vote-19th, pull requests merged in 2024-06, with the labels that each got.

#6 CI/CD 파이프라인 구축
  .github/workflows/cicd.yml
  Dockerfile
Labels: 🌎Environment

#4 회원 가입 기능 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/ceos/vote/common/domain/BaseTimeEntity.java
  src/main/java/ceos/vote/common/exception/BadRequestException.java
  src/main/java/ceos/vote/common/exception/DomainException.java
  src/main/java/ceos/vote/common/exception/ExceptionCode.java
  src/main/java/ceos/vote/common/exception/GlobalExceptionHandler.java
  src/main/java/ceos/vote/config/JpaAuditingConfig.java
  src/main/java/ceos/vote/config/SecurityConfig.java
  src/main/java/ceos/vote/user/application/UserService.java
  src/main/java/ceos/vote/user/domain/Part.java
  src/main/java/ceos/vote/user/domain/TeamName.java
  src/main/java/ceos/vote/user/domain/User.java
  src/main/java/ceos/vote/user/domain/repository/UserRepository.java
  src/main/java/ceos/vote/user/exception/AlreadyExistException.java
  src/main/java/ceos/vote/user/exception/UserException.java
  src/main/java/ceos/vote/user/presentation/UserController.java
  src/main/java/ceos/vote/user/presentation/dto/request/UserCreateRequest.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/ceos/vote/ApiTest.java
  src/test/java/ceos/vote/user/api/UserApiTest.java
  src/test/java/ceos/vote/user/application/UserServiceTest.java
  src/test/java/ceos/vote/user/domain/PartTest.java
  src/test/java/ceos/vote/user/domain/TeamNameTest.java
  src/test/java/ceos/vote/user/fixture/UserFixture.java
  src/test/java/ceos/vote/user/presentation/UserControllerTest.java
  src/test/java/ceos/vote/user/presentation/docs/UserDocs.java
  src/test/java/ceos/vote/user/presentation/dto/request/UserCreateRequestTest.java
  src/test/resources/application.yml
  src/test/resources/data/truncate.sql
Labels: ✨Feature

#5 로그인 구현
  build.gradle
  src/docs/asciidoc/user.adoc
  src/main/java/ceos/vote/auth/dto/PrincipalUserDetails.java
  src/main/java/ceos/vote/auth/dto/request/LoginDto.java
  src/main/java/ceos/vote/auth/service/PrincipalUserDetailsService.java
  src/main/java/ceos/vote/common/exception/ExceptionCode.java
  src/main/java/ceos/vote/common/exception/ExceptionResponse.java
  src/main/java/ceos/vote/config/SecurityConfig.java
  src/main/java/ceos/vote/jwt/JwtUtil.java
  src/main/java/ceos/vote/jwt/exception/InvalidJwtException.java
  src/main/java/ceos/vote/jwt/exception/LoginInfoParsingException.java
  src/main/java/ceos/vote/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/ceos/vote/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/ceos/vote/jwt/filter/JwtExceptionFilter.java
  src/main/java/ceos/vote/user/application/UserService.java
  src/main/java/ceos/vote/user/domain/repository/UserRepository.java
  src/main/java/ceos/vote/user/presentation/dto/request/UserCreateRequest.java
  src/main/resources/application.yml
  src/test/java/ceos/vote/jwt/JwtUtilTest.java
  src/test/java/ceos/vote/jwt/filter/JwtAuthenticationFilterTest.java
  src/test/java/ceos/vote/user/api/UserApiTest.java
  src/test/java/ceos/vote/user/application/UserServiceTest.java
  src/test/java/ceos/vote/user/presentation/UserControllerTest.java
  src/test/resources/application.yml
Labels: ✨Feature

#9 permission deny 에러로 인한 CI/CD 문제 해결
  .github/workflows/cicd.yml
Labels: 🐞Bug

#12 CORS 설정
  src/main/java/ceos/vote/config/CorsConfig.java
  src/main/java/ceos/vote/config/SecurityConfig.java
  src/main/java/ceos/vote/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/ceos/vote/jwt/filter/JwtAuthorizationFilter.java
Labels: 🌎Environment

#18 유저 전체 조회 API 작성
  src/docs/asciidoc/user.adoc
  src/main/java/ceos/vote/user/application/UserService.java
  src/main/java/ceos/vote/user/presentation/UserController.java
  src/test/java/ceos/vote/user/presentation/UserControllerTest.java
  src/test/java/ceos/vote/user/presentation/docs/UserDocs.java
Labels: ✨Feature

#20 투표시 0표 데이터 반환
  src/docs/asciidoc/vote.adoc
  src/main/java/ceos/vote/user/domain/User.java
  src/main/java/ceos/vote/vote/application/VoteService.java
  src/main/java/ceos/vote/vote/application/dto/response/DemodayVoteResponse.java
  src/main/java/ceos/vote/vote/application/dto/response/PartLeaderVoteResponse.java
  src/main/java/ceos/vote/vote/domain/repository/VoteRepository.java
  src/test/java/ceos/vote/vote/presentation/VoteControllerTest.java
  src/test/java/ceos/vote/vote/presentation/docs/VoteDocs.java
Labels: 🔨Refactor
